// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace TandemTechAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06917677-cdd6-4523-91b8-88d6d0a912d2"),
                            Email = "calexander@contosouniversity.edu",
                            FirstName = "Carson",
                            LastName = "Alexander"
                        },
                        new
                        {
                            Id = new Guid("798acf1b-7339-44bd-8367-7132a978d7b1"),
                            Email = "malonso@contosouniversity.edu",
                            FirstName = "Meredith",
                            LastName = "Alonso"
                        },
                        new
                        {
                            Id = new Guid("2a36409f-6732-459b-b7d1-a561c521a3cb"),
                            Email = "aanand@contosouniversity.edu",
                            FirstName = "Arturo",
                            LastName = "Anand"
                        },
                        new
                        {
                            Id = new Guid("7d84360e-4967-4c7b-8e4c-0f085de7ca4d"),
                            Email = "gbarzdukas@contosouniversity.edu",
                            FirstName = "Gytis",
                            LastName = "Barzdukas"
                        },
                        new
                        {
                            Id = new Guid("7a1be69a-38ac-4cde-a105-615de38c2d12"),
                            Email = "yli@contosouniversity.edu",
                            FirstName = "Yan",
                            LastName = "Li"
                        },
                        new
                        {
                            Id = new Guid("5e9c10d4-3b0a-4ccb-8a77-fb2d7e702c6b"),
                            Email = "pjustice@contosouniversity.edu",
                            FirstName = "Peggy",
                            LastName = "Justice"
                        },
                        new
                        {
                            Id = new Guid("53cea385-aa61-4e81-ba7a-38d7ed60ce4f"),
                            Email = "lnorman@contosouniversity.edu",
                            FirstName = "Laura",
                            LastName = "Norman"
                        },
                        new
                        {
                            Id = new Guid("554039c7-cba1-4404-9fbe-21918a9190f7"),
                            Email = "nolivetto@contosouniversity.edu",
                            FirstName = "Nino",
                            LastName = "Olivetto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
